trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # Best choice for Testcontainers (Linux containers)

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    version: '8.x'
    
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Agent.TempDirectory'
  inputs:
    targetPath: '$(Agent.TempDirectory)'
    artifact: TempDirectory 

- task: DotNetCoreCLI@2
  displayName: 'Run Integration Tests (with Testcontainers)'
  inputs:
    command: 'test'
    projects: '**/*Tests.Docker.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --verbosity "normal" --collect "Code coverage" --results-directory "/home/vsts/work/_temp/TestResults"'
# --results-directory $(Agent.TempDirectory)/TestResults'
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Agent.TempDirectory)/TestResults/**/*.trx'
    failTaskOnFailedTests: true
